<a href="https://colab.research.google.com/github/Mon6789/Deep-learning-/blob/main/fundamentals_of_tensor_flow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
constant_tensor=tf.constant([[5,9],[4,5]])

In [ ]:
print(constant_tensor)

tf.Tensor(
[[5 9]
 [4 5]], shape=(2, 2), dtype=int32)


In [ ]:
variable_tensor=tf.Variable([[5,9],[4,5]])


In [ ]:
print(variable_tensor)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 9],
       [4, 5]], dtype=int32)>


row concatenate


In [ ]:
row_concatenate=tf.concat(values=[constant_tensor,variable_tensor],axis=0)

In [ ]:
print( row_concatenate)

tf.Tensor(
[[5 9]
 [4 5]
 [5 9]
 [4 5]], shape=(4, 2), dtype=int32)


colum concatenate


In [ ]:
column_concatenate=tf.concat(values=[constant_tensor,variable_tensor],axis=1)

In [ ]:
print( column_concatenate)

tf.Tensor(
[[5 9 5 9]
 [4 5 4 5]], shape=(2, 4), dtype=int32)


zero tensor

In [ ]:
zeros=tf.zeros(shape=[2,2],dtype=tf.int32)

In [ ]:
print(zeros)

tf.Tensor(
[[0 0]
 [0 0]], shape=(2, 2), dtype=int32)


one tensor


In [ ]:
ones=tf.ones(shape=[5,3],dtype=tf.int32)

In [ ]:
print(ones)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]], shape=(5, 3), dtype=int32)


tensor transpose


In [ ]:
transpose=tf.transpose(variable_tensor)
print(variable_tensor)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 9],
       [4, 5]], dtype=int32)>


In [ ]:
print(transpose)

tf.Tensor(
[[5 4]
 [9 5]], shape=(2, 2), dtype=int32)


type conversion[change any data type]


In [ ]:
tensor_casting=tf.cast(transpose,tf.float32)

In [ ]:
print(tensor_casting)

tf.Tensor(
[[5. 4.]
 [9. 5.]], shape=(2, 2), dtype=float32)


reshape

In [ ]:
reshape=tf.reshape( tensor=row_concatenate,shape=[1,8])

In [ ]:
print(reshape)

tf.Tensor([[5 9 4 5 5 9 4 5]], shape=(1, 8), dtype=int32)


numpy to tensor


In [ ]:
import numpy as np
m=np.array([[3,2],[1,4]])

In [ ]:
m

array([[3, 2],
       [1, 4]])

In [ ]:
tf.convert_to_tensor(m)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[3, 2],
       [1, 4]])>

In [ ]:
m=np.array([[0,0],[1,4.3]])

In [ ]:
tf.convert_to_tensor(m)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0. , 0. ],
       [1. , 4.3]])>